# Numpy

# 

In [53]:
import numpy as np

# 1- D array

In [54]:
myarr= np.array([1,2,3,4])

In [55]:
print(myarr)

[1 2 3 4]


In [56]:
print(type(myarr))

<class 'numpy.ndarray'>


In [57]:
myarr.ndim        #   to check dimention of array

1

In [58]:
arr= np.array([1])

In [59]:
print(arr)

[1]


In [60]:
print(type(myarr))

<class 'numpy.ndarray'>


In [61]:
arr.ndim

1

# 2-D array

In [62]:
ar= np.array([[1,2,3], [2,3,4]])

In [63]:
print(ar)

[[1 2 3]
 [2 3 4]]


In [64]:
ar.ndim                #  2-D array

2

In [65]:
a= np.array([[1,2,3], [2,3,4], [5,6,7]])

In [66]:
a.ndim

2

# 3-D array

In [67]:
x= np.array([[[1,2,3], [3,4,5], [5,6,7]]])

In [68]:
print(x)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]]


In [69]:
x.ndim          # 3-D  array

3

In [70]:
x= np.array([[[1,2,3], [3,4,5]]])

In [71]:
x

array([[[1, 2, 3],
        [3, 4, 5]]])

In [72]:
x.ndim

3

# Numpy function - 

# zeros

In [73]:
np.zeros(4)

array([0., 0., 0., 0.])

In [74]:
np.zeros((2,4))         # 2 row , 4 column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.zeros((2, 4, 3))        # 2 matrix and 4 row 3 column

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# ones

In [76]:
np.ones(2)

array([1., 1.])

In [77]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.ones((2,1,10))          # 2 matrix   and 1 row   10  column

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [80]:
np.ones((2,3,5))         # 3 row  and 5 column

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# identity

In [81]:
np.identity(2)     # two by two matrix

array([[1., 0.],
       [0., 1.]])

In [82]:
np.identity(3)          # three by three matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.identity(4)         #   4 by 4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# arange

In [84]:
np.arange(4)       # (0 to n-1)

array([0, 1, 2, 3])

In [85]:
np.arange(4,10)       # 4 to 9

array([4, 5, 6, 7, 8, 9])

In [86]:
np.arange(4,10,2)

array([4, 6, 8])

In [87]:
np.arange(10,4,-2)

array([10,  8,  6])

# Empty

In [88]:
np.empty(7)            #  generate a random number

array([0., 0., 0., 0., 0., 0., 0.])

In [89]:
np.empty(3)

array([1., 1., 1.])

In [90]:
np.empty((5,2))     # 5 row 2 column

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0., 11.],
       [ 0.,  0.],
       [ 0.,  0.]])

# Linspace

In [91]:
np.linspace(2,4)     # Generate a random number between two range

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [92]:
np.linspace(2,6,3)   #    3 stopez  , between 3  to 6

array([2., 4., 6.])

In [93]:
np.linspace(2,6,7)         #   7 stopez

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        ])

# Axis =  0
# Axis = 1

In [94]:
ar1= np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [95]:
print(ar1)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [96]:
ar1.sum()    # sum of total number  from matrix

45

In [97]:
ar1.sum(axis=1)        # axis=1   for column

array([[12, 15, 18]])

In [98]:
ar1.sum(axis=0)        # axis=0   for row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Transpose

In [99]:
import numpy as np

In [100]:
a= np.array([[10,20,30], [23,34,45]])

In [101]:
a

array([[10, 20, 30],
       [23, 34, 45]])

In [102]:
a.T         # transpose of matrix

array([[10, 23],
       [20, 34],
       [30, 45]])

# Min & Max

In [144]:
arr= np.array([[[6,5,4],[4,1,8],[7,10,9]]])

In [145]:
print(arr)

[[[ 6  5  4]
  [ 4  1  8]
  [ 7 10  9]]]


In [146]:
arr.max()        # maximum  number present in array

10

In [147]:
arr.min()        # minimum number present in array

1

# argmax()  , argmin()

In [150]:
arr= np.array([[[6,5,4],[4,1,8],[7,10,9]]])

In [151]:
arr

array([[[ 6,  5,  4],
        [ 4,  1,  8],
        [ 7, 10,  9]]])

In [152]:
arr.argmax()           # index of maximum number

7

In [154]:
arr.argmin()            # index of minimum number

4

# argsort

In [107]:
import numpy as np

In [160]:
arr= np.array([[[6,5,4],[4,1,8],[7,10,9]]])

In [161]:
arr

array([[[ 6,  5,  4],
        [ 4,  1,  8],
        [ 7, 10,  9]]])

In [162]:
#arr.sort()

In [167]:
#arr

In [164]:
arr.argsort()    # to find index number    (first short then print index)

array([[[2, 1, 0],
        [1, 0, 2],
        [0, 2, 1]]], dtype=int64)

In [113]:
arr.sort()

In [114]:
arr

array([[[ 4,  5,  6],
        [ 1,  4,  8],
        [ 7,  9, 10]]])

In [115]:
arr.argsort()            # find index 

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]], dtype=int64)

# sum

In [116]:
arr

array([[[ 4,  5,  6],
        [ 1,  4,  8],
        [ 7,  9, 10]]])

In [117]:
arr.sum(axis=0)                 # (axis= 0)  for  row

array([[ 4,  5,  6],
       [ 1,  4,  8],
       [ 7,  9, 10]])

In [118]:
arr.sum(axis=1)                 # (axis= 1) for column

array([[12, 18, 24]])

# sqrt()

In [172]:
a= np.array([[[4,8,6],[18,9,4],[100,200,300]]])

In [173]:
a

array([[[  4,   8,   6],
        [ 18,   9,   4],
        [100, 200, 300]]])

In [174]:
np.sqrt(a)                     # square root 

array([[[ 2.        ,  2.82842712,  2.44948974],
        [ 4.24264069,  3.        ,  2.        ],
        [10.        , 14.14213562, 17.32050808]]])

# 

# Q.1- write a numpy program to create a 3*3 matrix 
# with value ranging from 2 to 10

In [119]:
import numpy as np
a= np.array([[[1,2,3],[3,4,5],[7,9,8]]])
print(a)
print()
print("dimention=",a.ndim)

[[[1 2 3]
  [3 4 5]
  [7 9 8]]]

dimention= 3


# Q.2- write a numpy program to create null vector 
#  of size 10 and update sixth value to 11

In [120]:
array= np.zeros(10)
print(array)
array[5]= 11
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


# Q3. write a numpy program to create an empty array

In [121]:
ar= np.array([])
print(ar)

[]
